apiVersion: v1
kind: Service
metadata:
  labels:
    app: udaconnect-location-producer
  name: udaconnect-location-producer
spec:
  ports:
  - name: 5005-5005
    nodePort: 30005
    port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    app: udaconnect-location-producer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udaconnect-location-producer
  name: udaconnect-location-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udaconnect-location-producer
  template:
    metadata:
      labels:
        app: udaconnect-location-producer
    spec:
      containers:
      - image: thonglevan131/udaconnect-location-producer:latest
        name: udaconnect-location-producer
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "256m"
        env:
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: TOPIC_NAME
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_SERVER
      restartPolicy: Always
